### ISSUE TITLE
Structured content 'if' statement does not work as expected. 

### ISSUE THREAD

**Issue by numbfall** [jakewies/jakewiesler.com#1]
Hello, your site is really beautiful. I was looking at your code and methods for inspiration and found something.

In `/layouts/partials/seo_schema.html` the if statement under `{{ if .IsPage }}` does not generate the `<script>` tag for any section other than the single blog view. 

I am assuming that you are expecting the list page, for example, to have the else part of the script. Anyways I wanted to do this and the following worked for me:

```html
<script type="application/ld+json">
    {{ if and (.IsPage) (eq .Section "blog") }}
        // json for 'blog'
    {{ else }}
        // default json
    {{ end }}
</script>
```

Note that `{{ if .IsHome }}` is not necessary now or it will duplicate the script on the home page.

**Comment by jakewies** [comment]
Hey @numbfall thanks for this! I had no idea that was happening. It's been a while since implemented the `seo_schema` partial and don't quite remember why I had that `else` statement. I'm going to go ahead and update my partial template to include your fix.

Thanks for the feedback and your great help! I'm glad my website could be a source of inspiration for you 😄

**Comment by jakewies** [comment]
Closed via https://github.com/jakewies/jakewiesler.com/commit/77feb017643ef5c627f96f4a51d91f318ee8f91d
